# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Trees and Robots"
description:        "A blog about programming and life in general written by @jacoscaz"

# URL
url:                "https://treesandrobots.com"
baseurl:            ""
permalink:          /:year/:month/:title.html

# Markdown
# Now unsupported by github pages
# markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "RSS"
    href:           "/feed.xml"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
