
# Basic
name:               "Trees and Robots"
description:        "A blog about programming and life in general written by @jacoscaz"

# URL
url:                "https://treesandrobots.com"
baseurl:            ""
permalink:          /:year/:month/:title.html

# Navigation
nav:
  - name:           "Home"
    href:           "/"
  - name:           "Writings"
    href:           "/writings.html"
    layout:         "post"
    rss:            "/feed.xml"
  - name:           "Syslog"
    href:           "/syslog.html"
    layout:         "syslog"
    rss:            "/feed-syslog.xml"
  - name:           "Now"
    href:           "/now.html"
  - name:           "About"
    href:           "/about.html"
  - name:           "Works"
    href:           "/works.html"
  - name:           "Things"
    href:           "/things.html"
  - name:           "Fitness"
    href:           "/fitness.html"

# Sass
sass:
  style:            :compressed


collections:
  syslog:
    output: false

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "syslog"
    values:
      layout:       "syslog"

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: false
