# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Trees and Robots"

# URL
#baseurl:            "/Kiko"
baseurl:            "" #For Root Domain
permalink:          /:year/:month/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "RSS"
    href:           "/feed.xml"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
